
version: 2

sources:
  - name: sources
    description: raw source data
    schema: main
    tables:
      - name: duty_codes
      - name: raw_school_base
      - name: raw_school_fields
      - name: raw_s275
  - name: ext
    description: data created outside SQL and the DAG, but is part of the DAG
    schema: main
    tables:
      - name: ext_teachermobility_distance
      - name: ext_schoolleadership_broad
